schema_version = 1

[package]
name = "metatensor-torch"
homepage = "https://docs.metatensor.org/"
description = "Metatensor-torch provides TorchScript bindings for metatensor."
license = "BSD-3-Clause"

[build]
easyblock = "CMakeNinja"
build_systems = ["CMake", "Ninja"]
moduleclass = "lib"

[build.easyconfig_parameters]
preconfigopts = { concat = [
  "export CMAKE_PREFIX_PATH=$EBROOTPYTORCH/lib/python3.12/site-packages/torch:$EBROOTMETATENSOR",
  "${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH} && ",
] }

[build.easyconfig_parameters.sanity_check_paths]
files = ["lib/libmetatensor_torch.so"]
dirs = ["include", "lib", "lib/cmake"]

[[dependencies.requirements]]
name = "Python"
constraint = "==3.14.2"

[[dependencies.requirements]]
name = "PyTorch"
constraint = "==2.9.1"

[[dependencies.requirements]]
name = "metatensor"
constraint = "==0.2.2"

[[profiles]]
name = "default"
default = true
config_options = [
  "-DBUILD_SHARED_LIBS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DTorch_DIR=$EBROOTPYTORCH/lib/python3.12/site-packages/torch/share/cmake/Torch",
]

[profiles.toolchain_options]
pic = true
openmp = true
