schema_version = 1

[package]
name = "quill"
homepage = "https://github.com/odygrd/quill"
description = "Quill is an asynchronous low-latency C++ logging library."
license = "MIT"

[build]
easyblock = "CMakeMake"
build_systems = ["CMake"]
moduleclass = "lib"

[[build.patches]]
filename = "quill-11.1.0_map-anon.patch"
sha256 = "0890d24573ade5cd0b1e86ee186022253e4596c16c588daf8bd68dc253544c72"
source = "patches/quill/quill-11.1.0_map-anon.patch"

[build.easyconfig_parameters.sanity_check_paths]
files = [
  "include/quill/Logger.h",
  "include/quill/Backend.h",
]
dirs = [
  "include/quill",
  "lib/cmake/quill",
]

[dependencies]
exclude_from_solve = ["make"]

[[dependencies.requirements]]
name = "binutils"
constraint = "==2.45"
roles = ["build"]

[[profiles]]
name = "default"
default = true
config_options = [
  "-DQUILL_BUILD_EXAMPLES=OFF",
  "-DQUILL_BUILD_TESTS=OFF",
  "-DQUILL_BUILD_BENCHMARKS=OFF",
  "-DQUILL_ENABLE_INSTALL=ON",
]

[profiles.toolchain_options]
pic = true
