{% set name = "quill" %}
{% set version = "11.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/odygrd/quill/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a4c41068ec51979e1c6d95ae9ab6efc09e654b9815dcb7a1b58b7a430a5cbd13
  patches:
    - patches/fix.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands:
    - test -d ${PREFIX}/include/quill
    - test -f ${PREFIX}/include/quill/Frontend.h

about:
  home: https://github.com/odygrd/quill
  license: MIT
  license_file: LICENSE
  summary: Asynchronous low-latency C++ logging library
  description: Quill is a high-performance asynchronous logging library for C++17 and later.
  doc_url: https://quillcpp.readthedocs.io/en/latest/
  dev_url: https://github.com/odygrd/quill
