# -- Project information -----------------------------------------------------
import os
import shutil

project = "eb-stack"
copyright = "2026, Rohit Goswami"
author = "Rohit Goswami"
release = "0.3.0"

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx_sitemap",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxcontrib_rust",
    "sphinx_rustdoc_postprocess",
]

templates_path = ["_templates"]
exclude_patterns = []

# -- Rust API (sphinxcontrib-rust + sphinx-rustdocgen) ------------------------
# Generated RST lives under docs/source/crates/eb_stack/ (pixi gen-rust-api).
_here = os.path.dirname(os.path.abspath(__file__))
_repo = os.path.abspath(os.path.join(_here, "../.."))
rust_crates = {
    "eb_stack": _repo,
}
rust_doc_dir = os.path.join(_here, "crates")
rust_rustdoc_fmt = "rst"
_rustdocgen = os.environ.get("SPHINX_RUSTDOCGEN") or shutil.which(
    "sphinx-rustdocgen"
)
if not _rustdocgen:
    _cargo_rustdocgen = os.path.expanduser("~/.cargo/bin/sphinx-rustdocgen")
    if os.path.isfile(_cargo_rustdocgen):
        _rustdocgen = _cargo_rustdocgen
if _rustdocgen:
    rust_rustdocgen = os.path.abspath(_rustdocgen)
# Pre-generated by scripts/gen-rust-api.sh; do not re-invoke rustdoc during
# sphinx-build (avoids a second compile). Use "always" only when debugging.
rust_generate_mode = "skip"

rustdoc_postprocess_toctree_target = "reference/rust-api.rst"
rustdoc_postprocess_toctree_rst = """
Rust API (``eb_stack``)
-----------------------

.. toctree::
   :maxdepth: 2

   ../crates/eb_stack/lib
   ../crates/eb_stack/main
"""

# -- Options for HTML output -------------------------------------------------
html_theme = "shibuya"
html_static_path = ["_static"]
html_favicon = "_static/favicon.svg"
html_title = "eb-stack documentation"
html_baseurl = "https://eb-stack.rgoswami.me/"
html_css_files = ["custom.css"]

html_context = {
    "source_type": "github",
    "source_user": "HaoZeke",
    "source_repo": "eb-stack",
    "source_version": "main",
    "source_docs_path": "/docs/orgmode/",
}

html_theme_options = {
    "github_url": "https://github.com/HaoZeke/eb-stack",
    "accent_color": "teal",
    "dark_code": True,
    "globaltoc_expand_depth": 1,
    "light_logo": "_static/logo-light.svg",
    "dark_logo": "_static/logo-dark.svg",
    "nav_links": [
        {
            "title": "Tutorial",
            "url": "tutorial",
        },
        {
            "title": "Annual bump",
            "url": "howto/run-annual-bump",
        },
        {
            "title": "CLI",
            "url": "reference/cli",
        },
        {
            "title": "Rust API",
            "url": "reference/rust-api",
        },
        {
            "title": "GitHub",
            "url": "https://github.com/HaoZeke/eb-stack",
            "external": True,
        },
    ],
}

html_sidebars = {
    "**": [
        "sidebars/localtoc.html",
        "sidebars/repo-stats.html",
        "sidebars/edit-this-page.html",
    ],
}


def _tracked_source_context(app, pagename, templatename, context, doctree):
    """Route edit links to tracked Org sources, not generated RST."""
    if pagename.startswith("crates/"):
        context["page_source_suffix"] = None
    else:
        context["page_source_suffix"] = ".org"


def setup(app):
    app.connect("html-page-context", _tracked_source_context)

# sphinx-sitemap
sitemap_url_scheme = "{link}"
